### ISSUE TITLE
Criar um readme.md deste repositório

### ISSUE THREAD

**Issue by Joaovictor163** [marcos-segantine/the-rick#1]
Olá, da para ter uma ideia geral vendo o código, mas achei interessante ver você usando ***Python*** do que se trata esse repositório?
obrigado !

**Comment by marcos-segantine** [comment]
É basicamente um algoritmo que rodará em uma placa Raspberry Pi, que funcionará como o cérebro de um robô cuja função será conversar com o público geral, provendo informações, por exemplo. Este robô é alimentado por uma inteligência artificial para que as respostas sejam geradas em tempo real. Ele também terá personalidade, sabendo qual é o seu nome (Rick), a cidade em que está localizado, etc. Informações mais específicas como essas são definidas no próprio código.
